import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen grid grid-cols-[auto_1fr] grid-rows-[auto_1fr]">
          <Sidebar />
          <div className="border-b py-4 px-6">Header</div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
